version: '3.8'

services:
  map_of_zones_dev:
    container_name: map_of_zones_dev
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - REACT_APP_GRAPH_QL_HTTP_URI=http://165.232.107.244:8081/v1/graphql
      - REACT_APP_GRAPH_QL_WS_URI=ws://165.232.107.244:8081/v1/graphql
