version: '3.8'

services:
  app:
    container_name: moz-web-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
